// Curated list of major OTB (Over The Board) backgammon tournaments.
// IMPORTANT: Always verify dates, entry fees, and format on the official website before paying.
// Data reflects typical/recurring annual events; specifics change each edition.
//
// To make the Videos tab "Watch" button play an embedded video instead of opening
// YouTube search, add one of these fields to a tournament:
//   featuredVideoId: "<youtube-video-id>"     — plays a single video
//   featuredPlaylistId: "<youtube-playlist-id>" — plays a full playlist
// Example: https://www.youtube.com/watch?v=Ow_-WNcpLKo → featuredVideoId: "Ow_-WNcpLKo"
// Example: https://www.youtube.com/playlist?list=PLA7Zca... → featuredPlaylistId: "PLA7Zca..."

const TOURNAMENTS = [
  {
    id: "monte-carlo",
    name: "Monte Carlo World Backgammon Championship",
    city: "Monte Carlo",
    country: "Monaco",
    region: "Europe",
    lat: 43.7384,
    lng: 7.4246,
    startDate: "2026-07-20",
    endDate: "2026-07-26",
    venue: "Fairmont Monte Carlo",
    format: "Knockout",
    divisions: ["Championship", "Intermediate", "Beginner", "Doubles", "Super Jackpot"],
    entryFeeUSD: 2000,
    prizePoolUSD: 250000,
    currency: "EUR",
    requirements: "Open to all. Championship division requires Championship-level rating or director approval. Dress code smart-casual in main hall.",
    payment: "Bank transfer in advance or cash at on-site registration (EUR/USD accepted). Major credit cards at venue.",
    clockUsed: true,
    notes: "Considered the most prestigious OTB event in the world. Hotel rooms book out months in advance.",
    website: "https://www.backgammon-montecarlo.com/",
    languages: ["English", "French"],
    featuredVideoId: "Ow_-WNcpLKo" // 2025 BGWC Final at Monte Carlo
  },
  {
    id: "nordic-open",
    name: "Nordic Open",
    city: "Copenhagen",
    country: "Denmark",
    region: "Europe",
    lat: 55.6761,
    lng: 12.5683,
    startDate: "2026-04-02",
    endDate: "2026-04-06",
    venue: "Scandic Copenhagen",
    format: "Swiss + Knockout",
    divisions: ["Championship", "Intermediate", "Novice", "Doubles", "Blitz", "Super Jackpots"],
    entryFeeUSD: 550,
    prizePoolUSD: 80000,
    currency: "DKK",
    requirements: "Open to all skill levels. Divisions assigned by self-rating or director review.",
    payment: "Online bank transfer in advance (discount) or card/cash at registration.",
    clockUsed: true,
    notes: "Largest Easter backgammon festival in Europe. Side events run continuously.",
    website: "https://www.backgammon.dk/nordicopen/",
    languages: ["English", "Danish"],
    featuredVideoId: "2DfQDW3jyUk" // 2025 Nordic Open Day 4 Grand Final
  },
  {
    id: "merit-open",
    name: "Merit Open",
    city: "Kyrenia",
    country: "Cyprus",
    region: "Europe",
    lat: 35.3417,
    lng: 33.3192,
    startDate: "2026-11-15",
    endDate: "2026-11-22",
    venue: "Merit Crystal Cove Hotel & Casino",
    format: "Swiss + Knockout",
    divisions: ["Championship", "Intermediate", "Beginner", "Seniors", "Ladies", "Doubles"],
    entryFeeUSD: 750,
    prizePoolUSD: 150000,
    currency: "EUR",
    requirements: "Open. Package deals with hotel typically offered.",
    payment: "Package booking via hotel, includes entry. Card and cash accepted.",
    clockUsed: true,
    notes: "All-inclusive resort event. Strong international field.",
    website: "https://merithotels.com/merit-open-backgammon/",
    languages: ["English", "Turkish"],
    featuredVideoId: "2UIUviTH1ow" // 8th Merit Open - Burak Sarıkaş
  },
  {
    id: "pba-championships",
    name: "PartyGammon / WBGF World Championship",
    city: "Antalya",
    country: "Turkey",
    region: "Europe",
    lat: 36.8969,
    lng: 30.7133,
    startDate: "2026-10-08",
    endDate: "2026-10-15",
    venue: "Titanic Beach Lara",
    format: "Knockout",
    divisions: ["Open Championship", "Women's", "Senior", "Team", "Pairs"],
    entryFeeUSD: 600,
    prizePoolUSD: 100000,
    currency: "EUR",
    requirements: "WBGF membership recommended for national team qualification. Open to public for main events.",
    payment: "Online registration with card payment. Cash accepted on-site.",
    clockUsed: true,
    notes: "Federation-style event with national team competitions alongside open play.",
    website: "https://wbgf.info/",
    languages: ["English"],
    featuredVideoId: "Kxgi4GjSyGU" // WBGF Team World Championship 2025
  },
  {
    id: "abt-chicago",
    name: "Chicago Open (ABT)",
    city: "Chicago",
    country: "USA",
    region: "North America",
    lat: 41.8781,
    lng: -87.6298,
    startDate: "2026-06-12",
    endDate: "2026-06-14",
    venue: "Westin Chicago Northwest, Itasca",
    format: "Single Elimination + Consolation",
    divisions: ["Championship", "Advanced", "Intermediate", "Novice", "Doubles", "Last Chance"],
    entryFeeUSD: 350,
    prizePoolUSD: 25000,
    currency: "USD",
    requirements: "USBGF membership not required but encouraged. ABT points awarded.",
    payment: "Pre-register online via USBGF site, or pay cash at door.",
    clockUsed: true,
    notes: "Part of the American Backgammon Tour. Friendly midwest crowd.",
    website: "https://usbgf.org/abt-american-backgammon-tour/",
    languages: ["English"],
    featuredVideoId: "fAQWeB--Eq8" // 2024 Chicago Open FINALS Stream 1
  },
  {
    id: "abt-carolina",
    name: "Carolinas Backgammon Championships",
    city: "Charlotte",
    country: "USA",
    region: "North America",
    lat: 35.2271,
    lng: -80.8431,
    startDate: "2026-03-13",
    endDate: "2026-03-15",
    venue: "Embassy Suites Charlotte",
    format: "Single Elimination + Consolation + Last Chance",
    divisions: ["Open", "Intermediate", "Novice", "Doubles", "Super Jackpot"],
    entryFeeUSD: 300,
    prizePoolUSD: 18000,
    currency: "USD",
    requirements: "Open to all. Self-select division (TD may move you up).",
    payment: "Cash or check at registration. Some pre-pay via PayPal.",
    clockUsed: true,
    notes: "Long-running ABT stop with reliable turnout.",
    website: "https://usbgf.org/abt-american-backgammon-tour/",
    languages: ["English"]
  },
  {
    id: "abt-michigan",
    name: "Michigan Summer Championships",
    city: "Novi",
    country: "USA",
    region: "North America",
    lat: 42.4806,
    lng: -83.4755,
    startDate: "2026-08-07",
    endDate: "2026-08-09",
    venue: "Sheraton Detroit Novi",
    format: "Single Elimination",
    divisions: ["Open", "Intermediate", "Novice", "Doubles", "Quickie"],
    entryFeeUSD: 300,
    prizePoolUSD: 15000,
    currency: "USD",
    requirements: "Open registration.",
    payment: "Cash or check on-site. Pre-registration discount available.",
    clockUsed: true,
    notes: "Hosted by the Motor City Backgammon Club.",
    website: "https://motorcitybackgammon.com/",
    languages: ["English"],
    featuredVideoId: "MLJIK2hz6eY" // 2024 Michigan Summer Backgammon Championship
  },
  {
    id: "abt-la",
    name: "Los Angeles Open",
    city: "Los Angeles",
    country: "USA",
    region: "North America",
    lat: 34.0522,
    lng: -118.2437,
    startDate: "2026-02-13",
    endDate: "2026-02-15",
    venue: "LAX Hilton",
    format: "Single Elimination + Consolation",
    divisions: ["Championship", "Advanced", "Intermediate", "Novice", "Doubles", "Speedgammon"],
    entryFeeUSD: 400,
    prizePoolUSD: 30000,
    currency: "USD",
    requirements: "Open. Director may reassign divisions for fairness.",
    payment: "On-site registration, cash/check preferred.",
    clockUsed: true,
    notes: "Largest west-coast ABT stop. Held over Presidents Day weekend.",
    website: "https://www.labackgammon.com/",
    languages: ["English"],
    featuredVideoId: "yMHL9shtLuQ" // Los Angeles Open 2024
  },
  {
    id: "abt-pittsburgh",
    name: "Pittsburgh Backgammon Open",
    city: "Pittsburgh",
    country: "USA",
    region: "North America",
    lat: 40.4406,
    lng: -79.9959,
    startDate: "2026-09-25",
    endDate: "2026-09-27",
    venue: "DoubleTree Pittsburgh",
    format: "Single Elimination",
    divisions: ["Open", "Intermediate", "Novice", "Doubles"],
    entryFeeUSD: 250,
    prizePoolUSD: 10000,
    currency: "USD",
    requirements: "Open registration.",
    payment: "Cash, check, or Venmo at registration.",
    clockUsed: true,
    notes: "Smaller club-run event with strong regular attendance.",
    website: "https://usbgf.org/abt-american-backgammon-tour/",
    languages: ["English"]
  },
  {
    id: "uk-open",
    name: "UK Open Backgammon Championships",
    city: "Coventry",
    country: "United Kingdom",
    region: "Europe",
    lat: 52.4068,
    lng: -1.5197,
    startDate: "2026-05-22",
    endDate: "2026-05-25",
    venue: "DoubleTree by Hilton Coventry",
    format: "Swiss + Knockout",
    divisions: ["Open", "Intermediate", "Beginner", "Doubles", "Ladies"],
    entryFeeUSD: 280,
    prizePoolUSD: 20000,
    currency: "GBP",
    requirements: "Open. UKBGF membership encouraged.",
    payment: "Bank transfer in advance or card on-site.",
    clockUsed: true,
    notes: "Held over the UK May bank holiday.",
    website: "https://ukbgf.com/",
    languages: ["English"],
    featuredVideoId: "qconLgO2Zeo" // UKBGF Women's Championship FINAL 2025
  },
  {
    id: "german-open",
    name: "German Open",
    city: "Munich",
    country: "Germany",
    region: "Europe",
    lat: 48.1351,
    lng: 11.5820,
    startDate: "2026-09-04",
    endDate: "2026-09-06",
    venue: "Holiday Inn Munich City Centre",
    format: "Swiss + Knockout",
    divisions: ["Open", "Intermediate", "Beginner", "Seniors", "Doubles"],
    entryFeeUSD: 350,
    prizePoolUSD: 18000,
    currency: "EUR",
    requirements: "Open. DBGV (German federation) membership encouraged.",
    payment: "Bank transfer or card at registration.",
    clockUsed: true,
    notes: "Run by the German Backgammon Federation (DBGV).",
    website: "https://www.backgammon-bund.de/",
    languages: ["German", "English"],
    featuredVideoId: "Wn5fzVCHojs" // 2024 Deutsche Backgammon Meisterschaft Main Final
  },
  {
    id: "italian-open",
    name: "Italian Open",
    city: "San Remo",
    country: "Italy",
    region: "Europe",
    lat: 43.8159,
    lng: 7.7761,
    startDate: "2026-06-26",
    endDate: "2026-06-28",
    venue: "Casino San Remo",
    format: "Swiss + Knockout",
    divisions: ["Open", "Intermediate", "Beginner", "Doubles"],
    entryFeeUSD: 400,
    prizePoolUSD: 25000,
    currency: "EUR",
    requirements: "Open. ID required at casino venue (18+).",
    payment: "Cash or card at casino registration desk.",
    clockUsed: true,
    notes: "Casino venue requires age ID. Smart dress code.",
    website: "https://www.fiabg.it/",
    languages: ["Italian", "English"],
    featuredVideoId: "ockb-Su3_m0" // 6th Rimini Open CNB final - Sanna vs Tudose
  },
  {
    id: "greek-open",
    name: "Greek Open",
    city: "Athens",
    country: "Greece",
    region: "Europe",
    lat: 37.9838,
    lng: 23.7275,
    startDate: "2026-05-08",
    endDate: "2026-05-10",
    venue: "Divani Caravel Hotel",
    format: "Swiss + Knockout",
    divisions: ["Open", "Intermediate", "Beginner", "Doubles", "Ladies"],
    entryFeeUSD: 300,
    prizePoolUSD: 20000,
    currency: "EUR",
    requirements: "Open. Greek federation membership available on-site.",
    payment: "Card or cash at registration.",
    clockUsed: true,
    notes: "Backgammon ('tavli') is part of Greek culture — large casual turnout in side events.",
    website: "https://www.hellenicbackgammon.gr/",
    languages: ["Greek", "English"],
    featuredVideoId: "1bgOVGCHRIM" // 3rd Greek Grand Prix - Mochy vs Roland Sahlén
  },
  {
    id: "dutch-open",
    name: "Dutch Open",
    city: "Amsterdam",
    country: "Netherlands",
    region: "Europe",
    lat: 52.3676,
    lng: 4.9041,
    startDate: "2026-10-30",
    endDate: "2026-11-01",
    venue: "Mövenpick Hotel Amsterdam City Centre",
    format: "Swiss + Knockout",
    divisions: ["Open", "Intermediate", "Beginner", "Doubles"],
    entryFeeUSD: 250,
    prizePoolUSD: 12000,
    currency: "EUR",
    requirements: "Open registration.",
    payment: "Bank transfer pre-event or card/cash on-site.",
    clockUsed: true,
    notes: "Compact weekend format, well-organized.",
    website: "https://www.nederlandsebackgammonbond.nl/",
    languages: ["Dutch", "English"]
  },
  {
    id: "stockholm-open",
    name: "Stockholm Open",
    city: "Stockholm",
    country: "Sweden",
    region: "Europe",
    lat: 59.3293,
    lng: 18.0686,
    startDate: "2026-11-06",
    endDate: "2026-11-08",
    venue: "Quality Hotel Globe",
    format: "Swiss + Knockout",
    divisions: ["Open", "Intermediate", "Doubles"],
    entryFeeUSD: 220,
    prizePoolUSD: 10000,
    currency: "SEK",
    requirements: "Open. SBGF membership available on-site.",
    payment: "Swish (Swedish mobile pay), card, or cash.",
    clockUsed: true,
    notes: "Swedish federation event with strong Nordic attendance.",
    website: "https://www.svenskbackgammon.se/",
    languages: ["Swedish", "English"],
    featuredVideoId: "8ZaEXIafNBA" // Swedish Galaxy Championship 2020 FINAL
  },
  {
    id: "czech-open",
    name: "Czech Open",
    city: "Prague",
    country: "Czech Republic",
    region: "Europe",
    lat: 50.0755,
    lng: 14.4378,
    startDate: "2026-07-03",
    endDate: "2026-07-05",
    venue: "OREA Hotel Pyramida",
    format: "Swiss + Knockout",
    divisions: ["Open", "Intermediate", "Beginner"],
    entryFeeUSD: 180,
    prizePoolUSD: 8000,
    currency: "EUR",
    requirements: "Open.",
    payment: "Card or cash at registration.",
    clockUsed: true,
    notes: "Held alongside other mind sports during Prague's annual mind-games festival.",
    website: "https://www.czechopen.net/",
    languages: ["Czech", "English"]
  },
  {
    id: "tokyo-open",
    name: "Japan Open",
    city: "Tokyo",
    country: "Japan",
    region: "Asia",
    lat: 35.6762,
    lng: 139.6503,
    startDate: "2026-11-21",
    endDate: "2026-11-23",
    venue: "Tokyo Bay Ariake Washington Hotel",
    format: "Swiss + Knockout",
    divisions: ["Open", "Intermediate", "Beginner", "Doubles"],
    entryFeeUSD: 200,
    prizePoolUSD: 8000,
    currency: "JPY",
    requirements: "Open. JBL (Japan Backgammon League) membership encouraged.",
    payment: "Cash (JPY) at registration. Limited card support.",
    clockUsed: true,
    notes: "JBL flagship event. Highly organized.",
    website: "https://backgammon.gr.jp/",
    languages: ["Japanese", "English"],
    featuredVideoId: "tw-sM1wo5Vk" // Japan Open 2024 Final - Mochy vs Ryo Matsuura
  },
  {
    id: "korea-open",
    name: "Korea Open",
    city: "Seoul",
    country: "South Korea",
    region: "Asia",
    lat: 37.5665,
    lng: 126.9780,
    startDate: "2026-08-22",
    endDate: "2026-08-23",
    venue: "Lotte Hotel World",
    format: "Swiss",
    divisions: ["Open", "Intermediate"],
    entryFeeUSD: 150,
    prizePoolUSD: 5000,
    currency: "KRW",
    requirements: "Open registration.",
    payment: "Cash or local card at registration.",
    clockUsed: true,
    notes: "Growing event with friendly community.",
    website: "https://www.kbgf.org/",
    languages: ["Korean", "English"],
    featuredPlaylistId: "PLA7ZcagI0frAZn0cO-XaamCIFlN9DDZAm" // Korea Open 2024 playlist
  },
  {
    id: "australian-open",
    name: "Australian Open",
    city: "Melbourne",
    country: "Australia",
    region: "Oceania",
    lat: -37.8136,
    lng: 144.9631,
    startDate: "2026-10-03",
    endDate: "2026-10-05",
    venue: "Bayview Eden Melbourne",
    format: "Single Elimination",
    divisions: ["Open", "Intermediate", "Novice", "Doubles"],
    entryFeeUSD: 250,
    prizePoolUSD: 10000,
    currency: "AUD",
    requirements: "Open. ABF membership available at venue.",
    payment: "Card or cash on-site.",
    clockUsed: true,
    notes: "Australian Backgammon Federation's flagship event.",
    website: "https://www.backgammon.org.au/",
    languages: ["English"],
    featuredPlaylistId: "PLRtZwZ6CFwtT_N5uTWlvQDktab6rU2pWO" // 2023 Australian Backgammon Championship Gold Coast playlist
  },
  {
    id: "israel-open",
    name: "Israeli Open",
    city: "Tel Aviv",
    country: "Israel",
    region: "Middle East",
    lat: 32.0853,
    lng: 34.7818,
    startDate: "2026-12-04",
    endDate: "2026-12-06",
    venue: "Dan Panorama Tel Aviv",
    format: "Swiss + Knockout",
    divisions: ["Open", "Intermediate", "Beginner", "Doubles"],
    entryFeeUSD: 300,
    prizePoolUSD: 15000,
    currency: "ILS",
    requirements: "Open registration.",
    payment: "Card, cash, or local bank transfer.",
    clockUsed: true,
    notes: "Backgammon ('shesh-besh') has a huge casual following in Israel.",
    website: "https://www.backgammon.org.il/",
    languages: ["Hebrew", "English"],
    featuredVideoId: "LQtDj4MCS3Y" // Israel Backgammon Championship
  },
  {
    id: "rio-open",
    name: "Rio Open",
    city: "Rio de Janeiro",
    country: "Brazil",
    region: "South America",
    lat: -22.9068,
    lng: -43.1729,
    startDate: "2026-09-18",
    endDate: "2026-09-20",
    venue: "Windsor Atlantica",
    format: "Swiss",
    divisions: ["Open", "Intermediate"],
    entryFeeUSD: 200,
    prizePoolUSD: 7000,
    currency: "BRL",
    requirements: "Open.",
    payment: "Local PIX, card, or cash.",
    clockUsed: true,
    notes: "Growing South American scene.",
    website: "https://www.cbgamao.com.br/",
    languages: ["Portuguese", "English"]
  },
  {
    id: "vegas-open",
    name: "Las Vegas Open",
    city: "Las Vegas",
    country: "USA",
    region: "North America",
    lat: 36.1699,
    lng: -115.1398,
    startDate: "2026-01-23",
    endDate: "2026-01-25",
    venue: "Riviera Convention area / Westgate",
    format: "Single Elimination + Consolation",
    divisions: ["Championship", "Advanced", "Intermediate", "Novice", "Doubles", "Super Jackpots"],
    entryFeeUSD: 500,
    prizePoolUSD: 50000,
    currency: "USD",
    requirements: "Open. Strong international field — Championship division can be tough.",
    payment: "Cash or check preferred at registration.",
    clockUsed: true,
    notes: "Combines an ABT stop with massive side action.",
    website: "https://usbgf.org/abt-american-backgammon-tour/",
    languages: ["English"],
    featuredVideoId: "jmf0wvEp64g" // 2023 U.S. Open Las Vegas FINALS Stream 1
  },
  {
    id: "boston-open",
    name: "Boston Open",
    city: "Boston",
    country: "USA",
    region: "North America",
    lat: 42.3601,
    lng: -71.0589,
    startDate: "2026-11-13",
    endDate: "2026-11-15",
    venue: "Marriott Newton",
    format: "Single Elimination",
    divisions: ["Open", "Intermediate", "Novice", "Doubles"],
    entryFeeUSD: 275,
    prizePoolUSD: 12000,
    currency: "USD",
    requirements: "Open.",
    payment: "Cash, check, Venmo on-site.",
    clockUsed: true,
    notes: "Run by Boston Backgammon club.",
    website: "https://www.bostonbackgammon.com/",
    languages: ["English"]
  },
  {
    id: "newyork-open",
    name: "New York Metropolitan Open",
    city: "New York",
    country: "USA",
    region: "North America",
    lat: 40.7128,
    lng: -74.0060,
    startDate: "2026-04-24",
    endDate: "2026-04-26",
    venue: "Crowne Plaza White Plains",
    format: "Single Elimination + Consolation",
    divisions: ["Championship", "Intermediate", "Novice", "Doubles"],
    entryFeeUSD: 325,
    prizePoolUSD: 18000,
    currency: "USD",
    requirements: "Open registration.",
    payment: "Cash or check preferred.",
    clockUsed: true,
    notes: "Tristate area regulars; ABT stop.",
    website: "https://nybackgammon.com/",
    languages: ["English"],
    featuredVideoId: "Kbz9l1d7dug" // NY Metropolitan Open ABT Online Final Day Stream
  },
  {
    id: "paris-open",
    name: "Paris Open",
    city: "Paris",
    country: "France",
    region: "Europe",
    lat: 48.8566,
    lng: 2.3522,
    startDate: "2026-03-27",
    endDate: "2026-03-29",
    venue: "Cercle Haussmann",
    format: "Swiss + Knockout",
    divisions: ["Open", "Intermediate", "Beginner", "Doubles"],
    entryFeeUSD: 280,
    prizePoolUSD: 15000,
    currency: "EUR",
    requirements: "Open. FFBG membership encouraged.",
    payment: "Card or cash at registration.",
    clockUsed: true,
    notes: "French Federation event; cercle (private club) venue.",
    website: "https://www.ffbg.fr/",
    languages: ["French", "English"],
    featuredVideoId: "F9nANXBZdJA" // Championnats de France de backgammon 2022 à Sèvres
  }
];
